apiVersion: v1
kind: Service
metadata:
  name: backend-librarian
  labels:
    app.kubernetes.io/name: backend-librarian
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend-librarian
  ports:
    - name: http
      port: 80
      targetPort: http
