# 개발 환경에서 base ConfigMap 위에 덮어쓸 값
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-librarian-config
data:
  APP_ENV: 'development'
  DEPLOYMENT_ENV: 'dev'
  OTEL_SERVICE_NAME: 'backend-librarian'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector.monitoring.svc.cluster.local:4318'
  OTEL_TRACES_SAMPLER_ARG: '1.0'
